services:
  python-ip:
    build: ./dev/
    container_name: 'python-IP'
    working_dir: '/root/src/'
    tty: true
    volumes:
      - ~/Documents/IP:/root/src
      - ~/.config/pulse:/root/.config/pulse
    environment:
      - DISPLAY=host.docker.internal:0
      - PULSE_SERVER=host.docker.internal
